### ISSUE TITLE
docker 运行1.1版本出现了错误

### ISSUE THREAD

**Issue by ndaydayup** [ShilongLee/Crawler#13]
/bin/sh: 1: port: not found
Usage: uvicorn [OPTIONS] APP
Try 'uvicorn --help' for help.

Error: Invalid value for '--port': 'main:app' is not a valid integer.

**Comment by ndaydayup** [comment]
丢给gpt说是未指定端口 

这个错误信息表明你在使用 uvicorn 运行一个 ASGI 应用时，提供了一个无效的端口值。错误提示中提到的 --port 选项需要一个整数值，但是错误信息显示 'main:app' 被错误地用作了端口值。

uvicorn 是一个用于运行 ASGI 应用的服务器。当你运行 uvicorn 时，你需要指定你的应用对象，格式通常是 模块名:应用实例。例如，如果你的应用在 main.py 文件中，并且定义了一个名为 app 的 ASGI 应用实例，你应该这样启动 uvicorn：

bash
uvicorn main:app --port 8000
在这个命令中：

main 是包含 ASGI 应用实例的 Python 文件的名称（不包括 .py 扩展名）。
app 是在 main.py 文件中定义的 ASGI 应用实例的名称。
--port 8000 指定了服务器监听的端口号，你应该将其替换为你想要的端口号。
如果你看到的错误信息是由于你将应用路径和端口号混合在了一起，你需要将它们分开，确保格式正确。例如，如果你的应用路径是 my_project.main:application，并且你想要监听端口 8000，你应该这样写：

bash
uvicorn my_project.main:application --port 8000
请确保：

使用正确的模块和应用实例路径。
端口号是一个有效的整数。
命令格式符合 uvicorn 的要求。

**Comment by ShilongLee** [comment]
已修复，感谢您的建议🙏
