### ISSUE TITLE
抖音的好像已经不行了

### ISSUE THREAD

**Issue by xiaogewujiu** [ShilongLee/Crawler#16]
抖音的好像已经不行了，通过生成的a_bogus 接口响应200但是没有数任何数据了

**Comment by ShilongLee** [comment]
是不是你cookie过期了，刚刚尝试了一下是有返回的，如果是想单独使用加密算法，可以看我的代码学习一下。

**Comment by xiaogewujiu** [comment]
我是通过api接口添加了一个账号，再使用detail接口时 返回 请先添加账号。cookie都是再浏览器中通过打开抖音然后 document.cookie 获取的

**Comment by ShilongLee** [comment]
没错你的使用流程是正确的，但是我不确定每个请求发送的cookie是否是一样的，你可以同fetch/xhr中获取发送请求时带的cookie。可以参考一下这个接口的获取cookie。
https://github.com/ShilongLee/Crawler/wiki/%E6%8A%96%E9%9F%B3

**Comment by ShilongLee** [comment]
看看快速上手，检查一下有没有不一致的地方，如果没有可以在目录中的.log下看看是否有错误日志。
https://github.com/ShilongLee/Crawler/wiki/%E5%BF%AB%E9%80%9F%E4%B8%8A%E6%89%8B
