### ISSUE TITLE
服务器部署后能否直接利用网页端操作？

### ISSUE THREAD

**Issue by cauzp** [ShilongLee/Crawler#20]
尊敬的作者您好，非常感谢您提供的高质量工作！
我在云服务器上利用docker部署了您的项目，并放通了8080端口，但是无法直接利用公网ip地址:8080/douyin/add-acount的方式添加账号信息，您能提供进一步的支持吗？
非常感谢您为开源社区做出的杰出贡献！

**Comment by ShilongLee** [comment]
add_account试试，不是-哦

**Comment by cauzp** [comment]
![image](https://github.com/user-attachments/assets/928c2154-7204-49ee-a10a-e1e03d4b1926)
感谢您的回复，事实上我复制粘贴的readme中的命令，将localhost改为了公网ip利用浏览器进行访问，结果如下图所示。

**Comment by ShilongLee** [comment]
看到了，首先接口使用的是post请求，其次body是json。我建议你可以尝试使用postman或者apipost工具发送请求。可以看我的快速上手。

**Comment by ShilongLee** [comment]
Body里使用参数

**Comment by ShilongLee** [comment]
使用json格式

**Comment by cauzp** [comment]
感谢回复，基本上跑起来了，我再调试一下看看怎么把内容存下来

**Comment by magicjiaxia** [comment]
可以问问怎么搭建吗，装了宝塔

**Comment by ShilongLee** [comment]
> 可以问问怎么搭建吗，装了宝塔

安装docker，然后一键启动
sudo docker run -d --name crawler -p 8080:8080 registry.cn-hangzhou.aliyuncs.com/shilongli0101/crawler:latest   # 国内镜像源

**Comment by magicjiaxia** [comment]
> > 可以问问怎么搭建吗，装了宝塔
> 
> 安装Docker，然后一键启动sudo docker run-d--name Crawler-p8080:8080注册表。中国大陆-杭州。aliyuncs.com/shilongli0101/crawler：最新#国内镜像源
这样安装docker那宝塔里面能管理docker吗，怎么把镜像弄进去，没用过这个

**Comment by ShilongLee** [comment]
> > > 可以问问怎么搭建吗，装了宝塔
> > 
> > 安装Docker，然后一键启动sudo docker run-d--name Crawler-p8080:8080注册表。中国大陆-杭州。aliyuncs.com/shilongli0101/crawler：最新#国内镜像源
> 这样安装docker那宝塔里面能管理docker吗，怎么把镜像弄进去，没用过这个
> 

这个命令会自动下载镜像并运行，管理镜像输入docker images

**Comment by magicjiaxia** [comment]
> > > > 可以问问怎么搭建吗，装了宝塔
> > > 
> > > 
> > > 安装Docker，然后一键启动sudo docker run-d--name Crawler-p8080:8080注册表。中国大陆-杭州。aliyuncs.com/shilongli0101/crawler：最新#国内镜像源
> > > 这样安装docker那宝塔里面能管理docker吗，怎么把镜像弄进去，没用过这个
> 
> 这个命令会自动下载镜像并运行，管理镜像输入docker images

大佬，可以给个联系方式吗，请教请教

**Comment by ShilongLee** [comment]
> 大佬，可以给个联系方式吗，请教请教
联系我的邮箱吧lishilong0101@gmail.com
