### ISSUE TITLE
小红书又不行了

### ISSUE THREAD

**Issue by it-tin** [ShilongLee/Crawler#22]
作者大大，小红书算法又不行了，在网站复制js代码用你的环境也不行，可能加了环境检测，大佬有时间看看呗：
![image](https://github.com/user-attachments/assets/fbd7b075-9e51-4fc5-8052-a1b57ed8bbde)

**Comment by it-tin** [comment]
搞错了，没问题，是这个xsec_token，应该怎么获取啊？
![image](https://github.com/user-attachments/assets/4f6f3a13-cbb5-4ae7-9304-23d666d924ec)

**Comment by ShilongLee** [comment]
目前没加这个参数，这个没有也可以正常访问

**Comment by it-tin** [comment]
> 目前没加这个参数，这个没有也可以正常访问

我这没这个参数不行，但是写死就可以访问，现在我是直接写死的，就怕以后这个参数会变动

**Comment by ShilongLee** [comment]
已修复，小红书强制检查了xsec_token，我从doc请求中动态获取了。
