### ISSUE TITLE
添加账号后请求还是会提示请先添加账号

### ISSUE THREAD

**Issue by lengyanwl** [ShilongLee/Crawler#23]
RT，用别的服务器部署也是会这样提示

**Comment by ShilongLee** [comment]
看看.log下面有没有error

**Comment by lengyanwl** [comment]
我看日志里是这样的来。461。[2024-07-27 15:29:50,363][SingletonLogger][INFO]: (/app/service/xhs/logic/common.py:64) url: https://edith.xiaohongshu.com/api/sns/web/v1/feed, params: {'source_note_id': '64132c260000000013033738', 'image_formats': ['jpg', 'webp', 'avif'], 'extra': {'need_body_topic': '1'}}, response, code: 461, body: {"code":0,"success":true,"msg":"成功","data":{}}

**Comment by ShilongLee** [comment]
看起来有可能更新加密算法了，还有一种可能是cookie过期了，你尝试更新一下cookie，如果还不行的话我明天更新一下算法。

**Comment by lengyanwl** [comment]
嗯嗯，小红书用新cookie也不行，应该是更新算法了。我测试其他平台例如快手等，添加账号和请求都是正常的

**Comment by ShilongLee** [comment]
已修复，小红书强制检查了xsec_token，我从doc请求中动态获取了。

**Comment by lengyanwl** [comment]
好的！大佬牛比！
