### ISSUE TITLE
后续可以支持知乎文章的获取吗

### ISSUE THREAD

**Issue by xiaogewujiu** [ShilongLee/Crawler#24]
后续可以支持知乎文章的获取吗

**Comment by ShilongLee** [comment]
之前搞过知乎的盐选字体反爬破解，不好开源毕竟是付费内容。

**Comment by xiaogewujiu** [comment]
就正常的用户文章 问答之类的呢？ 我看了下是需要x-zse-96和x-zst-81这两个加密算法。感觉有点难没搞出来

**Comment by ShilongLee** [comment]
近期的话没打算新加平台，如果大佬想自己研究并开源的话，也欢迎大佬的贡献。
