### ISSUE TITLE
抖音的个人主页视频列表获取不到

### ISSUE THREAD

**Issue by W-CLL** [ShilongLee/Crawler#27]
抖音的个人主页视频列表获取不到（其他接口都可以正常获取），是有什么限制还是需要登录cookie

**Comment by ShilongLee** [comment]
可以获取的到啊，检查一下是不是用户id搞错了，获取的作品结果在awewe_list里面。
用户id获取看我wiki中，抖音部分获取用户id。

**Comment by W-CLL** [comment]
用户id没错的，同一个接口/douyin/user，只返回了信息，但是awewe_list是空的

**Comment by ShilongLee** [comment]
看一下.log下有没有ERROR报错，其次看一下该用户是否发表过作品

**Comment by W-CLL** [comment]
没有报错信息，哈哈，我自己的抖音号，有作品

**Comment by W-CLL** [comment]
试了几个都不行，我再调试看看，如果解决了请告诉我，谢谢了

**Comment by ShilongLee** [comment]
你看看日志中通有没有报错，看看/aweme/v1/web/aweme/post/接口返回值是什么

**Comment by W-CLL** [comment]
request error，但是状态码是200，body返回是空，没有很多的错误信息反馈了

**Comment by ShilongLee** [comment]
request headers中有 cookie 吗

**Comment by W-CLL** [comment]
用的是user接口，作者信息能获取到，应该有cookie值吧

**Comment by ShilongLee** [comment]
cookie需要调用接口添加，最好看日志确认一下，你是没有添加cookie吗。

**Comment by W-CLL** [comment]
有的，接口调用也存在，日志我也加了打印，也存在cookie，请求没有返回任何数据所以不知道什么原因了

**Comment by ShilongLee** [comment]
更新一下cookie试试，我这边本地调试了一下是正常的。

**Comment by ShilongLee** [comment]
或者看一下wiki，看看是不是有什么遗漏得地方。

**Comment by W-CLL** [comment]
哈哈，我刚更新了cookie，一样获取不到，参数没错，接口没错，我再看看吧

**Comment by W-CLL** [comment]
我换了个电脑win10，Python 3.12.3, node v21.6.1重新部署一遍，复制cookie去请求都没获取到 ，aweme_list 还是空的，日志也是没啥返回，应该不关浏览器设置问题吧，header都写死了，linux环境我都部署一次了，还是获取不到。大佬！要是有其他人有这种问题解决了告诉我一声

**Comment by ShilongLee** [comment]
![image](https://github.com/user-attachments/assets/e60a986e-fa97-4afa-979e-0ae3f649c8e1)
刚才又试了一下，你再试试吧，看看日志之类的。

**Comment by W-CLL** [comment]
找到原因了，改一下就行了，我不知道你本地是不是改了没更新，还是因为版本问题，这个Fasle自动转换为字符串类型
![40731232750](https://github.com/user-attachments/assets/14e5fff6-f9eb-41e6-b8c9-dab42edb495f)
