### ISSUE TITLE
tb搜索返回结果的问题

### ISSUE THREAD

**Issue by LeToNode** [ShilongLee/Crawler#32]
从代码来看，实现是根据用户输入的页码，一直执行到该页结束获取所有的结果。
目前执行下来有几个问题：
1. 如果真的选择50页或者100页，这个执行时间会很长，正常请求接口会有超时的问题。
2. 返回结果中总是会有将原始的data里面的作为数组的第一个结果返回。初步怀疑是results对象使用错误引起。
3. 如果连续执行期间出现验证码是否会停止并返回还是跳过继续呢？

**Comment by ShilongLee** [comment]
1.确实会有这个问题，这个是为了兼容翻页而存在，但是淘宝的翻页只能一页一页翻，这个无法避免，除非维护缓存。
2.这个可能是代码问题，待检查。
3.连续执行期间出现验证码，如果无法json解析则会报错，否则继续，不会察觉到其中的异常，除非查看日志。

**Comment by ShilongLee** [comment]
2已确认为代码bug，现已修复。
