### ISSUE TITLE
xhs参数xsec_token校验问题

### ISSUE THREAD

**Issue by it-tin** [ShilongLee/Crawler#38]
现在随便用个xsec_token去请求获取不了内容了，有什么办法解决吗：
![image](https://github.com/user-attachments/assets/9458ba20-376e-4760-bb1c-9deacc1da451)

**Comment by limingluzhu** [comment]
同问

**Comment by ShilongLee** [comment]
这个是服务器推荐流下发的token。之前是一个token所有帖子都可以用，但是现在只能是一个帖子用对应的下发的token了。
所以现在唯一的办法就是到doc中获取数据了
https://www.xiaohongshu.com/explore/{note_id}
然后从下面这个里面获取了
window.__INITIAL_STATE__
明天有时间我会支持一下。
或者你们有想练手的可以提个PR。

**Comment by limingluzhu** [comment]
[https://www.xiaohongshu.com/explore/{note_id}](https://www.xiaohongshu.com/explore/%7Bnote_id%7D) 这个地址在访问时，好像也是需要token信息才可以，如果没有token会被重定向到首页 ，如果token不符，页面会提示访问异常。 这个有的解吗？

![image](https://github.com/user-attachments/assets/09ee01f6-28fa-4713-a9e4-6240aaff039f)

**Comment by ShilongLee** [comment]
> [https://www.xiaohongshu.com/explore/{note_id}](https://www.xiaohongshu.com/explore/%7Bnote_id%7D) 这个地址在访问时，好像也是需要token信息才可以，如果没有token会被重定向到首页 ，如果token不符，页面会提示访问异常。 这个有的解吗？
> 
> ![image](https://private-user-images.githubusercontent.com/5736258/357054130-09ee01f6-28fa-4713-a9e4-6240aaff039f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0NjgzMjksIm5iZiI6MTcyMzQ2ODAyOSwicGF0aCI6Ii81NzM2MjU4LzM1NzA1NDEzMC0wOWVlMDFmNi0yOGZhLTQ3MTMtYTllNC02MjQwYWFmZjAzOWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTJUMTMwNzA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWM1MTE5ODEwZDczYTA1NWQxYzc0NmY0MWUyMWVmZWFmMmU3YjEzMWJlMmUxNDI4MTA4ZWM4YTgxMjQwZGMyNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.svbEZHf3xUUUR6SxgQvip6tKgW1eWAmOccI5KILSoUk)
不会的啊，https://www.xiaohongshu.com/explore/66b9cafe0000000025031823，你再试试

**Comment by ShilongLee** [comment]
已修复，拉最新代码就可以了。

**Comment by it-tin** [comment]
我把加密参数去掉后又可以了，估计xhs不久后会修复这个bug：
![image](https://github.com/user-attachments/assets/00061372-9c77-4bbe-8bcd-17eeaf56f525)

**Comment by limingluzhu** [comment]
这里是不是需要在账号登录的条件下，才可以从doc中获取到token
