### ISSUE TITLE
改成nodejs后a_bogus只能生成一次

### ISSUE THREAD

**Issue by QQOQ** [ShilongLee/Crawler#4]
如题，改成nodejs后a_bogus只有第一次请求时候可以生成，第二次就生成不了，什么问题呢

**Comment by ShilongLee** [comment]
把什么改成nodejs了

**Comment by QQOQ** [comment]
> 把什么改成nodejs了

也不是改，是直接用`/lib/js/douyin.js` 生成的a_bogus去请求接口，只能使用一次，第二次无法生成，但是ctal+c中断后再启动可以，每次启动只能一次有效

**Comment by ShilongLee** [comment]
a_bogus是根据请求参数和useragent生成的，确认下你的参数有没有改变，然后运行node lib/is/douyin.js生成参数。

**Comment by QQOQ** [comment]
`const axios = require('axios');
const {sign_datail} = require('./abogus')
const express = require('express')
const crypto = require('crypto');
const app = express()
const port = 3006

function msToken(length) {
    const characters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
    const randomBytes = crypto.randomBytes(length);
    return Array.from(randomBytes, byte => characters[byte % characters.length]).join('');
}

let headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36",
    "sec-fetch-site": "same-origin",
    "sec-fetch-mode": "cors",
    "sec-fetch-dest": "empty",
    "sec-ch-ua-platform": "Windows",
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua": '"Not/A)Brand";v="8", "Chromium";v="126", "Google Chrome";v="126"',
    "referer": "https://www.douyin.com/?recommend=1",
    "priority": "u=1, i",
    "pragma": "no-cache",
    "cache-control": "no-cache",
    "accept-language": "zh-CN,zh;q=0.9,en;q=0.8",
    "accept": "application/json, text/plain, */*",
    "dnt": "1",
}

let params = {
    device_platform: 'webapp',
    aid: '6383',
    channel: 'channel_pc_web',
    aweme_id: '7370143938188971299',
    update_version_code: '170400',
    pc_client_type: '1',
    version_code: '190500',
    version_name: '19.5.0',
    cookie_enabled: 'true',
    screen_width: '1920',
    screen_height: '1280',
    browser_language: 'zh-CN',
    browser_platform: 'MacIntel',
    browser_name: 'Edge',
    browser_version: '124.0.0.0',
    browser_online:  'true',
    engine_name: 'Blink',
    engine_version: '124.0.0.0',
    os_name: 'Mac OS',
    os_version: '10.15.7',
    cpu_core_num: '6',
    device_memory: '8',
    platform: 'PC',
    downlink: '10',
    effective_type: '4g',
    round_trip_time: '50',
    webid: '7326515686162712075',
    verifyFp: 'verify_lwdp7m9r_JPMSjV9G_JtjY_43pE_B6eD_xGYC9dTb57sO',
    fp: 'verify_lwdp7m9r_JPMSjV9G_JtjY_43pE_B6eD_xGYC9dTb57sO',
    msToken: msToken(128)
}
params_str = new URLSearchParams(params).toString()

app.post('/get_aweme_detail', (req, res) => {
    const msTokenStr = msToken(107)
    params_str = new URLSearchParams(params).toString()

    const a_bogus = sign_datail(params_str, headers['User-Agent'])
    console.log('a_bogus',a_bogus)
    res.json({code: 200, msg: a_bogus})
})

app.listen(port, () => {
  console.log(`Example app listening on port ${port}`)
})
`
你试下这段代码，用post请求http://127.0.0.1:3006/get_aweme_detail，只有第一次可以生成a_bogus，第二次就不行了

**Comment by ShilongLee** [comment]
项目中使用正常生成，你再调试一下吧。
