### ISSUE TITLE
为什么抖音总是报错，取不到数据

### ISSUE THREAD

**Issue by hybfly** [ShilongLee/Crawler#41]
报错数据如下（我已经按要求添加了账号的，抖音网页版登录了，也按要求从里面把cookie复制到帐号的 cookie 中了）：
{
    "code": 3,
    "msg": "请先添加账号",
    "data": null
}

**Comment by ShilongLee** [comment]
看看日志中有没有报错

**Comment by hybfly** [comment]
日志中没有报错：
Active code page: 65001
PS F:\douyin\crawler> & "C:/Program Files (x86)/Python/python.exe" f:/douyin/crawler/main.py
INFO:     Started server process [12368]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)
INFO:     127.0.0.1:15531 - "GET /douyin/detail?id=7404192573331393843 HTTP/1.1" 200 OK
INFO:     127.0.0.1:15599 - "GET /douyin/detail?id=7404192573331393843 HTTP/1.1" 200 OK

**Comment by hybfly** [comment]
![Uploading QQ20240828-191427.png…]()

**Comment by hybfly** [comment]
![QQ20240828-191427](https://github.com/user-attachments/assets/c81b8b9a-ede2-4080-83e4-422f3bb72a84)

**Comment by hybfly** [comment]
调用账号查询接口也能看到我已添加了账号

**Comment by ShilongLee** [comment]
感觉你的cookie不太对呢，我刚才试了一下是好使的
<img width="1610" alt="image" src="https://github.com/user-attachments/assets/551debea-ce9d-4105-9859-afed7dfd9c48">

**Comment by ShilongLee** [comment]
https://www.douyin.com/video/7362005336229678387
你进这个视频，然后打开控制台，过滤detail，然后从这个请求头中复制cookie试试

**Comment by hybfly** [comment]
还是一样，我这里复制的cookie内容如下：SEARCH_RESULT_LIST_TYPE=%22single%22; UIFID_TEMP=29d6bea3e5a6c157a08a212e1912b5e8a78666ece26be56100fa19e58a63a45b22df8b94d19f9921747f3ff280532579bb62996de42b845f8eb28e43f9a5e120582b50e97ef9ec781a75545e770cd749; UIFID=29d6bea3e5a6c157a08a212e1912b5e8a78666ece26be56100fa19e58a63a45b4b6d4994f75b98fb717316c4f4f25b2d09bfe7b4bedd1fd42d613c0882f81b0aed91825ecd11a5f58f5720da5b6c885234b4f272f9fb4142fee5c9b4efc21c78c07d287653dd3efb22ad56ed1f910038d39e029d76c4ad4b8fb496649b81c19ed96ae8f90396aa034098315149833ff203b142a3a7c380a03226086a0348243c; ttwid=1%7C1mns0-vOWAeyuKZYk0Vgt8J7LePCnaPIKzGOr826N6s%7C1721707325%7Cd88d5436a8df1d73123794c16d2c64b03c46882cfe786116ca5175b9a3f195e5; hevc_supported=true; strategyABtestKey=%221724813932.095%22; passport_csrf_token=5dd24a9beb8130117713f04900a7dcfc; passport_csrf_token_default=5dd24a9beb8130117713f04900a7dcfc; bd_ticket_guard_client_web_domain=2; FORCE_LOGIN=%7B%22videoConsumedRemainSeconds%22%3A180%2C%22isForcePopClose%22%3A1%7D; d_ticket=4bcc8b43ce72c92f25476ea91b3f68c7bc29e; n_mh=4ij9gXOTR_vVzt-ti5aiT7Wg6J2BaWCsXF-tCIfM3pM; passport_auth_status=8f41905155010c3c5246c40da0696a3a%2C; passport_auth_status_ss=8f41905155010c3c5246c40da0696a3a%2C; is_staff_user=false; SelfTabRedDotControl=%5B%5D; _bd_ticket_crypt_doamin=2; __security_server_data_status=1; publish_badge_show_info=%220%2C0%2C0%2C1724827338118%22; store-region=cn-zj; store-region-src=uid; pwa2=%220%7C0%7C3%7C0%22; download_guide=%223%2F20240828%2F0%22; _bd_ticket_crypt_cookie=742385bc9e4abaefd6bbbd5f6567d073; volume_info=%7B%22isUserMute%22%3Atrue%2C%22isMute%22%3Atrue%2C%22volume%22%3A0.6%7D; FOLLOW_NUMBER_YELLOW_POINT_INFO=%22MS4wLjABAAAAIeD2xz9ft_QF_9Rto_bURbtDdfQXdya8Uo27cXZnW80%2F1724860800000%2F0%2F1724836706966%2F0%22; FOLLOW_LIVE_POINT_INFO=%22MS4wLjABAAAAIeD2xz9ft_QF_9Rto_bURbtDdfQXdya8Uo27cXZnW80%2F1724860800000%2F0%2F1724837346410%2F0%22; my_rd=2; sid_guard=d0bcfebb931514a1a8fac78775415037%7C1724837348%7C21600%7CWed%2C+28-Aug-2024+15%3A29%3A08+GMT; uid_tt=5bfb985ca13749077e3c26d7fdf07ef8; uid_tt_ss=5bfb985ca13749077e3c26d7fdf07ef8; sid_tt=d0bcfebb931514a1a8fac78775415037; sessionid=d0bcfebb931514a1a8fac78775415037; sessionid_ss=d0bcfebb931514a1a8fac78775415037; sid_ucp_v1=1.0.0-KDM0YmI4OTIxNDEzNWI3YjM1MzU1NTI3ZDk1NGUzZTJmOWYzNzQ3YjUKCBDk27u2BhgNGgJsZiIgZDBiY2ZlYmI5MzE1MTRhMWE4ZmFjNzg3NzU0MTUwMzc; ssid_ucp_v1=1.0.0-KDM0YmI4OTIxNDEzNWI3YjM1MzU1NTI3ZDk1NGUzZTJmOWYzNzQ3YjUKCBDk27u2BhgNGgJsZiIgZDBiY2ZlYmI5MzE1MTRhMWE4ZmFjNzg3NzU0MTUwMzc; odin_tt=d33aaf3a2e75068ef3a2995c813f7009f6654ea09a9096d17e40ab3d62cf54b947370170974d8b9812d71520891bb4e6caba2a189f718b2fe5d3d2df3777a69c; bd_ticket_guard_client_data=eyJiZC10aWNrZXQtZ3VhcmQtdmVyc2lvbiI6MiwiYmQtdGlja2V0LWd1YXJkLWl0ZXJhdGlvbi12ZXJzaW9uIjoxLCJiZC10aWNrZXQtZ3VhcmQtcmVlLXB1YmxpYy1rZXkiOiJCSWNGRnVLc1dyNmp4b2ZSaTlYMXJ0STduNEIxZUs4T1VNR2NINFFtSzduZ2t5bUQ4Ylk5eDR4L2xYME5EUlJmYlFEMGtwOSsxamlDQ3dvdWc0cWtoSU09IiwiYmQtdGlja2V0LWd1YXJkLXdlYi12ZXJzaW9uIjoxfQ%3D%3D; biz_trace_id=7444378e; WallpaperGuide=%7B%22showTime%22%3A1724828846304%2C%22closeTime%22%3A0%2C%22showCount%22%3A1%2C%22cursor1%22%3A21%2C%22cursor2%22%3A0%2C%22hoverTime%22%3A1724840108985%7D; stream_player_status_params=%22%7B%5C%22is_auto_play%5C%22%3A0%2C%5C%22is_full_screen%5C%22%3A0%2C%5C%22is_full_webscreen%5C%22%3A0%2C%5C%22is_mute%5C%22%3A1%2C%5C%22is_speed%5C%22%3A1%2C%5C%22is_visible%5C%22%3A0%7D%22; IsDouyinActive=true; home_can_add_dy_2_desktop=%220%22; stream_recommend_feed_params=%22%7B%5C%22cookie_enabled%5C%22%3Atrue%2C%5C%22screen_width%5C%22%3A1920%2C%5C%22screen_height%5C%22%3A1080%2C%5C%22browser_online%5C%22%3Atrue%2C%5C%22cpu_core_num%5C%22%3A4%2C%5C%22device_memory%5C%22%3A8%2C%5C%22downlink%5C%22%3A4.55%2C%5C%22effective_type%5C%22%3A%5C%224g%5C%22%2C%5C%22round_trip_time%5C%22%3A100%7D%22

**Comment by hybfly** [comment]
![2](https://github.com/user-attachments/assets/ebc8426c-75eb-49e8-9c10-d2121f3f06b0)

**Comment by hybfly** [comment]
另外，我看 https://www.douyin.com/video/7362005336229678387 中调用的是 https://www-hj.douyin.com/aweme/v1/web/aweme/detail/ 这个网址，我把 HOST = 'https://www.douyin.com' 改为 HOST = 'https://www-hj.douyin.com' 也不行，可能是抖音又改了代码吧，里面的参数可能也有调整，我也再研究下吧。

**Comment by ShilongLee** [comment]
我这边也是同样的域名，看起来没什么问题，换一个账号或者ip试试呢

**Comment by Echo-TCY221** [comment]
你好我抖音请求评论时遇到同样的情况
添加账户返回为
{"code":0,"msg":"OK","data":null}
获取评论返回为
{'code': 3, 'msg': '请先添加账号', 'data': None}
<img width="1559" alt="1725352671960" src="https://github.com/user-attachments/assets/83d6e1ef-91bb-4382-88bb-5f37c826cafc">
<img width="757" alt="1725352685281" src="https://github.com/user-attachments/assets/ec1e92a7-0f12-4203-b3f1-45908406d8da">

**Comment by Echo-TCY221** [comment]
![image](https://github.com/user-attachments/assets/0ec5f0e0-11c4-4d61-9be3-eec0028a3bfd)
我查看到cookie已经存入数据库中了

**Comment by Echo-TCY221** [comment]
已解决，又新写了一个测试请求的代码重新添加了一遍cookie就可以了
