### ISSUE TITLE
小红书最新的xs算法有大佬搞定了吗

### ISSUE THREAD

**Issue by xiaoyixiaoba** [ShilongLee/Crawler#43]
冒昧问下，用以前的js文件算出来的xs已经不能用了吧~

**Comment by ShilongLee** [comment]
上午试过还可以的

**Comment by xiaogewujiu** [comment]
今天试了好几次。换了几次cookie。小红书都获取不到列表了

**Comment by xiaoyixiaoba** [comment]
> 今天试了好几次。换了几次cookie。小红书都获取不到列表了

应该是xs算法变化了，原来的js生成的xs已经获取不到feed、comment这些数据了。
静待大佬们更新~

**Comment by ShilongLee** [comment]
<img width="1628" alt="image" src="https://github.com/user-attachments/assets/4ae986b5-d4dc-4d2f-ab7b-d72ee266bd4c">
为什么我这里可以，是不是账号被ban了，换一个账号和ip试试。

**Comment by 51881175** [comment]
我也不行. 抓评论的就显示{'code': -1, 'success': False}

**Comment by ShilongLee** [comment]
哦哦，我抓的是详情是可以的，明天我看看吧。

**Comment by xiaoyixiaoba** [comment]
> 哦哦，我抓的是详情是可以的，明天我看看吧。

你的详情是从doc里获取的，不需要xs就没问题，如果从feed接口获取就不行了，包括评论和搜索等等。

**Comment by ShilongLee** [comment]
确实，看到了，明天我修复一下。

**Comment by xiaoyixiaoba** [comment]
把新的加密代码给抠出来，验证可用。
我就直接把代码贴这里，懒得PR了哈，大佬可以验证下。[<script src="https://gist.github.com/xiaoyixiaoba/6d6ad539769252cbe2ed8737e98a00b9.js"></script>](https://gist.github.com/xiaoyixiaoba/6d6ad539769252cbe2ed8737e98a00b9)

**Comment by ShilongLee** [comment]
已修复，拉一下最新代码就好了。

**Comment by maryjeck** [comment]
> 把新的加密代码给抠出来，验证可用。 我就直接把代码贴这里，懒得PR了哈，大佬可以验证下。[<script src="https://gist.github.com/xiaoyixiaoba/6d6ad539769252cbe2ed8737e98a00b9.js"></script>](https://gist.github.com/xiaoyixiaoba/6d6ad539769252cbe2ed8737e98a00b9)

好像get的能用，post的不能用
