### ISSUE TITLE
小红书detail接口code返回为3

### ISSUE THREAD

**Issue by IianWang** [ShilongLee/Crawler#45]
![image](https://github.com/user-attachments/assets/54946405-4211-4ac0-a6c7-f79ae437dcd0)
![image](https://github.com/user-attachments/assets/bdf92446-6044-4de7-b793-a1e279c050b0)
![image](https://github.com/user-attachments/assets/5fa1ebfe-ff9e-4293-b559-c6fe99977046)

为什么有的时候返回为0，有的时候返回为3？

ps: 在请求之前确认有添加id和cookie

**Comment by ShilongLee** [comment]
日志有报错信息吗

**Comment by IianWang** [comment]
> 日志有报错信息吗

![image](https://github.com/user-attachments/assets/7104d45c-5cd0-4273-a971-5d5f215e43e9)

这个是crawler.log文件中内容

**Comment by ShilongLee** [comment]
刚刚试了一下好像是没问题的，是不是cookie过期了
<img width="1064" alt="image" src="https://github.com/user-attachments/assets/e829fe74-00fa-4243-8ee7-483d5b410d10">

**Comment by IianWang** [comment]
> 刚刚试了一下好像是没问题的，是不是cookie过期了 <img alt="image" width="1064" src="https://private-user-images.githubusercontent.com/72864711/367219401-e829fe74-00fa-4243-8ee7-483d5b410d10.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzMDEzOTEsIm5iZiI6MTcyNjMwMTA5MSwicGF0aCI6Ii83Mjg2NDcxMS8zNjcyMTk0MDEtZTgyOWZlNzQtMDBmYS00MjQzLThlZTctNDgzZDViNDEwZDEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE0VDA4MDQ1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmOGFiMjJkMGQ5YmM3MDlmNTg1NWI1NWNmNjI5OWNiOTNhZWJjZDlhYzdjMjNjMTU4OTgxMDI0MWYyNmQyNzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vo_frYBtI9ypD7kUb_WFDY_OpGdgNwjfu4v2V6BhrJY">

难道是cookie被风控了？我当时也登了网页版浏览了一些笔记

**Comment by ShilongLee** [comment]
> > 刚刚试了一下好像是没问题的，是不是cookie过期了 <img alt="image" width="1064" src="https://private-user-images.githubusercontent.com/72864711/367219401-e829fe74-00fa-4243-8ee7-483d5b410d10.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzMDEzOTEsIm5iZiI6MTcyNjMwMTA5MSwicGF0aCI6Ii83Mjg2NDcxMS8zNjcyMTk0MDEtZTgyOWZlNzQtMDBmYS00MjQzLThlZTctNDgzZDViNDEwZDEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE0VDA4MDQ1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmOGFiMjJkMGQ5YmM3MDlmNTg1NWI1NWNmNjI5OWNiOTNhZWJjZDlhYzdjMjNjMTU4OTgxMDI0MWYyNmQyNzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vo_frYBtI9ypD7kUb_WFDY_OpGdgNwjfu4v2V6BhrJY">
> 
> 难道是cookie被风控了？我当时也登了网页版浏览了一些笔记

很有可能

**Comment by maryjeck** [comment]
我来挖个坟。  @ShilongLee 小红薯他好像会检查ja3指纹，我看原来源码，请求试用httpx做的，有些时候请求过不去。我用其他修改ja3指纹的方式，其他接口也能用，这里提醒一下老大，是不是考虑一下加入修改ja3的部分

**Comment by ShilongLee** [comment]
> 我来挖个坟。 @ShilongLee 小红薯他好像会检查ja3指纹，我看原来源码，请求试用httpx做的，有些时候请求过不去。我用其他修改ja3指纹的方式，其他接口也能用，这里提醒一下老大，是不是考虑一下加入修改ja3的部分

我认为是可以的，只要该手段的确会增加接口稳定性。
