### ISSUE TITLE
哥，能不能出一个获取今日头条用户文章的呢？

### ISSUE THREAD

**Issue by luoxuandong** [ShilongLee/Crawler#47]
哥能不能出一个获取今日头条用户文章的呢？输入用户首页，获取用户的文章列表

**Comment by ShilongLee** [comment]
之前写过爬取抖音的文章你可以参考一下，我没有研究过今日头条，但我猜测应该是大同小异的
[CSDN](https://blog.csdn.net/weixin_48673014/article/details/139601829?fromshare=blogdetail&sharetype=blogdetail&sharerId=139601829&sharerefer=PC&sharesource=weixin_48673014&sharefrom=from_link)
