### ISSUE TITLE
淘宝的查询商品详情，好像失效了

### ISSUE THREAD

**Issue by maryjeck** [ShilongLee/Crawler#49]

**Comment by ShilongLee** [comment]
刚才试了一下还是可以的
<img width="1159" alt="image" src="https://github.com/user-attachments/assets/1f9f529e-4ab7-4b49-8c35-7beea06af87d">
是不是过期了，或者淘宝商品id不对。获取商品id[看这里](https://github.com/ShilongLee/Crawler/wiki/%E6%B7%98%E5%AE%9D)

**Comment by maryjeck** [comment]
{"code":0,"msg":"成功","data":{"url":"https://bixi.alicdn.com/punish/punish:resource:template:baba:default_33233685.html?qrcode=em72VlP1l1MzHMQYB4gpdg|ZuuC7g|KMEb-Q_0&uuid=7a6ef65653f59753331cc41807882976&action=deny&origin=https%3A%2F%2Fh5api.m.taobao.com%2Fh5%2Fmtop.taobao.pcdetail.data.get%2F1.0%2F%3Fjsv%3D2.6.1%26appKey%3D12574478%26t%3D1726710510159%26sign%3D3b2c8e252f52130a662d6387a4fba105%26api%3Dmtop.taobao.pcdetail.data.get%26v%3D1.0%26isSec%3D0%26ecode%3D0%26timeout%3D10000%26ttid%3D2022%2540taobao_litepc_9.17.0%26AntiFlood%3Dtrue%26AntiCreep%3Dtrue%26dataType%3Djson%26valueType%3Dstring%26preventFallback%3Dtrue%26type%3Djson%26data%3D%257B%2522id%2522%253A%2522693469008511%2522%252C%2522detail_v%2522%253A%25223.3.2%2522%252C%2522exParams%2522%253A%2522%257B%255C%2522id%255C%2522%253A%255C%2522693469008511%255C%2522%252C%255C%2522item_type%255C%2522%253A%255C%2522ad%255C%2522%252C%255C%2522ali_refid%255C%2522%253A%255C%2522a3_431358_1007%253A15572659%253AH%253A15572659_0_11770813889%253Ac0a3730368049201836ac06218cb19dd%255C%2522%252C%255C%2522ali_trackid%255C%2522%253A%255C%2522296_c0a3730368049201836ac06218cb19dd%255C%2522%252C%255C%2522spm%255C%2522%253A%255C%2522a21bo.jianhua%252Fa.201876.d5%255C%2522%252C%255C%2522scm%255C%2522%253A%255C%25221007.40986.397407.0%255C%2522%252C%255C%2522queryParams%255C%2522%253A%255C%2522ali_refid%253Da3_431358_1007%25253A15572659%25253AH%25253A15572659_0_11770813889%25253Ac0a3730368049201836ac06218cb19dd%2526ali_trackid%253D296_c0a3730368049201836ac06218cb19dd%2526id%253D693469008511%2526item_type%253Dad%2526scm%253D1007.40986.397407.0%2526spm%253Da21bo.jianhua%25252Fa.201876.d5%255C%2522%252C%255C%2522domain%255C%2522%253A%255C%2522https%253A%252F%252Fitem.taobao.com%255C%2522%252C%255C%2522path_name%255C%2522%253A%255C%2522%252Fitem.htm%255C%2522%257D%2522%257D&pureDenyWait="}}

**Comment by maryjeck** [comment]
这个是我的返回

**Comment by ShilongLee** [comment]
被风控了吧

**Comment by maryjeck** [comment]
但是网页浏览很正常，我就不知道了

**Comment by maryjeck** [comment]
发现问题了，我放在良心云上用，结果悲剧了，ip应该被识别了
