### ISSUE TITLE
好像评论最多只能采集49条

### ISSUE THREAD

**Issue by vitflash** [ShilongLee/Crawler#52]
http://127.0.0.1:8080/douyin/comments?id=7408870138604244287&offset=0&limit=120

url中的limit配置120 视频真实评论1000多条，不过只能采集49条
![image](https://github.com/user-attachments/assets/08b8ea97-ff05-4fbc-bd40-9144f8fca0ac)

**Comment by ShilongLee** [comment]
目前抖音接口支持的翻页个数好像有限，你改成limit 20，一页一页翻试试

**Comment by vitflash** [comment]
确实是这样的，第一次请求limit 是5条，offset 为0 后面再次请求，每次会增加20条 limit是20 offset是25 45 65 这个样子，不过我发现比如我评论区有781条，但是这个offset只会到740条就结束了。大佬，有空改下哈。

另外抖音的评论好像无法按照时间来排序 无固定的排序规则

**Comment by ShilongLee** [comment]
总有评论会不可见之类的，很正常

**Comment by vitflash** [comment]
感谢大佬的工具。
![image](https://github.com/user-attachments/assets/676e14e8-5b69-4e07-96f1-f6f25696b7d5)
我大概修改了下代码。去翻页来做的。不过大佬，有几个问题想请教下
1：如果频繁去请求会不会被封ip
2：如果使用代理，我登录ip和代理ip不一致。cookie会不会失效。
3：因为他不可以按照时间排序，所以我估计后面我要一直循环我配置的这些短视频数据了。抓取最新的留言

**Comment by ShilongLee** [comment]
1: 会
2: 不会
3: 可以拿出来然后按时间排序

**Comment by vitflash** [comment]
好的，感谢大佬，
