### ISSUE TITLE
怎么判断用户cookie是否有效呢。是否有哪个接口之类的

### ISSUE THREAD

**Issue by vitflash** [ShilongLee/Crawler#54]
你好，怎么判断用户的cookie是否有效呢，可以爬取到数据就是有效么，好像用户不登录也可以爬取到评论

**Comment by ShilongLee** [comment]
cookie无效一般指过期了，或者被服务器作废了，判断cookie无效在不被风控的情况下，可以获取其中的expire信息来作为判断依据。

**Comment by vitflash** [comment]
感谢
