### ISSUE TITLE
搜索接口怎么用

### ISSUE THREAD

**Issue by Hao1617** [ShilongLee/Crawler#63]
**url:**(https://www.douyin.com/aweme/v1/web/general/search/single/)
a_bogus怎么使用

**Comment by ShilongLee** [comment]
关于加密使用，请查看源码。
需要使用接口，可以查看接口文档和wiki。
如果有更具体的问题可以抛出来讨论一下。

**Comment by Hao1617** [comment]
sign_datail
sign_reply搜索使用哪个函数生成

**Comment by ShilongLee** [comment]
> sign_datail sign_reply搜索使用哪个函数生成

建议使用项目接口哈。想学习加密请查看源码。
可以参考这个文章辅助学习
https://blog.csdn.net/weixin_48673014/article/details/139601829?spm=1001.2014.3001.5501

**Comment by Hao1617** [comment]
好嘞 谢谢，你这个算法出售嘛 怎么联系

**Comment by ShilongLee** [comment]
> 好嘞 谢谢，你这个算法出售嘛 怎么联系

已经是开源的了。

**Comment by Hao1617** [comment]
不是还有个arguments参数嘛，不同接口参数应该不一样吧

**Comment by Hao1617** [comment]
> > sign_datail sign_reply搜索使用哪个函数生成
> 
> 建议使用项目接口哈。想学习加密请查看源码。 可以参考这个文章辅助学习 https://blog.csdn.net/weixin_48673014/article/details/139601829?spm=1001.2014.3001.5501

大佬，抖音更新了 与文档的不一致了。。。

**Comment by ShilongLee** [comment]
> > > sign_datail sign_reply搜索使用哪个函数生成
> > 
> > 
> > 建议使用项目接口哈。想学习加密请查看源码。 可以参考这个文章辅助学习 https://blog.csdn.net/weixin_48673014/article/details/139601829?spm=1001.2014.3001.5501
> 
> 大佬，抖音更新了 与文档的不一致了。。。

是的，但是原理是一样的，按照流程走一遍就好了。

**Comment by Hao1617** [comment]
> > > > sign_datail sign_reply搜索使用哪个函数生成
> > > 
> > > 
> > > 建议使用项目接口哈。想学习加密请查看源码。 可以参考这个文章辅助学习 https://blog.csdn.net/weixin_48673014/article/details/139601829?spm=1001.2014.3001.5501
> > 
> > 
> > 大佬，抖音更新了 与文档的不一致了。。。
> 
> 是的，但是原理是一样的，按照流程走一遍就好了。

好嘞 我摸索摸索

**Comment by Hao1617** [comment]
![image](https://github.com/user-attachments/assets/c5917fea-633b-475f-a462-a731c63363e0)
大佬，最后一步没有看懂，找到函数之后呢
![image](https://github.com/user-attachments/assets/1b8bb9b7-45bf-46d9-94ec-e3ae1904efd2)
断点到y函数这里了
