### ISSUE TITLE
试着获取直播间信息失败了

### ISSUE THREAD

**Issue by CrazyMelody** [ShilongLee/Crawler#65]
大佬你好，我尝试新增 api ，/webcast/room/web/enter/，参数也是拿的正常请求中的数据，使用common_request 返回失败了

是参数有什么特定要求么？还是签名计算需要额外适配才行？

**Comment by ShilongLee** [comment]
不一样的接口，他的加密函数的后面的三个参数不一样的。比如帖子详情接口和获取评论接口他们的参数就不一样，我的douyin.js代码中有体现。你可以直接调试到加密入口，看看参数是什么。
