### ISSUE TITLE
添加账号显示【Method Not Allowed】

### ISSUE THREAD

**Issue by qq263424205** [ShilongLee/Crawler#67]
http://localhost:8080/xhs/add_account

返回
{
    "detail": "Method Not Allowed"
}

请问怎么解决呢？

**Comment by ymgcs** [comment]
你这明显没有按照文档操作，不会用，那就仔细看文档

**Comment by ShilongLee** [comment]
> http://localhost:8080/xhs/add_account
> 
> 返回 { "detail": "Method Not Allowed" }
> 
> 请问怎么解决呢？

参数放在body里，用post请求。
可以参考一下[wiki](https://github.com/ShilongLee/Crawler/wiki/%E5%BF%AB%E9%80%9F%E4%B8%8A%E6%89%8B)

**Comment by qq263424205** [comment]
> > http://localhost:8080/xhs/add_account
> > 返回 { "detail": "不允许的方法" }
> > 请问怎么解决呢？
> 
> 参数放在body里，用post请求。 可以参考一下[wiki](https://github.com/ShilongLee/Crawler/wiki/%E5%BF%AB%E9%80%9F%E4%B8%8A%E6%89%8B)

参数已经传了

**Comment by ymgcs** [comment]
> > > http://localhost:8080/xhs/add_account
> > > 返回 { "detail": "不允许的方法" }
> > > 请问怎么解决呢？
> > 
> > 
> > 参数放在body里，用post请求。 可以参考一下[wiki](https://github.com/ShilongLee/Crawler/wiki/%E5%BF%AB%E9%80%9F%E4%B8%8A%E6%89%8B)
> 
> 参数已经传了

按照这样格式{"id": "dy", "cookie": "你的cookie"}

**Comment by qq263424205** [comment]
![企业微信截图_20241026113343](https://github.com/user-attachments/assets/fd18f3e7-4399-452c-8a32-c1f52d951dc9)


> > > > http://localhost:8080/xhs/add_account
> > > > 返回 { "detail": "不允许的方法" }
> > > > 请问怎么解决呢？
> > > 
> > > 
> > > 参数放在body里，用post请求。 可以参考一下[wiki](https://github.com/ShilongLee/Crawler/wiki/%E5%BF%AB%E9%80%9F%E4%B8%8A%E6%89%8B)
> > 
> > 
> > 参数已经传了
> 
> 按照这样格式{"id": "dy", "cookie": "你的cookie"}

**Comment by qq263424205** [comment]
> > > > http://localhost:8080/xhs/add_account
> > > > 返回 { "detail": "不允许的方法" }
> > > > 请问怎么解决呢？
> > > 
> > > 
> > > 参数放在body里，用post请求。 可以参考一下[wiki](https://github.com/ShilongLee/Crawler/wiki/%E5%BF%AB%E9%80%9F%E4%B8%8A%E6%89%8B)
> > 
> > 
> > 参数已经传了
> 
> 按照这样格式{"id": "dy", "cookie": "你的cookie"}

![Uploading 企业微信截图_20241026113343.png…]()

**Comment by qq263424205** [comment]
![企业微信截图_20241026113343](https://github.com/user-attachments/assets/afaa669d-db4a-439b-a531-8357c5b61a63)

**Comment by ShilongLee** [comment]
是POST请求，不是GET

**Comment by qq263424205** [comment]
好吧，我错了
