### ISSUE TITLE
请问是否有方法直接将这个部署在 Railway 上

### ISSUE THREAD

**Issue by nanjade** [ShilongLee/Crawler#7]
我想制作一个 API 给手机端用

**Comment by ShilongLee** [comment]
现在还没支持哦，非常好的意见，issue先open着，很快就会支持这个功能。

**Comment by ShilongLee** [comment]
大佬，我试了一下，不知道为什么我的github账号虽然获取到了railway的免费额度，但是没有部署权限。
我看了设置中，有设置启动命令，你可以直接设置为make run启动就好了。由于启动命令简单且我这边没办法实操就暂且不支持railway的部署配置文件了。感谢大佬支持🙏
