### ISSUE TITLE
抖音评论

### ISSUE THREAD

**Issue by W-CLL** [ShilongLee/Crawler#74]
想问一直只能拿第一页内容，第二页就拿不到了，是因为cookie问题还是代理问题，会导致一直拿不到第二页，或者有其他原因需要加入什么参数

**Comment by ShilongLee** [comment]
也有可能跟翻页有关，抖音的接口不支持太大的翻页个数。

**Comment by W-CLL** [comment]
没有错误返回，就是请求成功，拿到空数据，事实上是有第二页数据的 ，根据偏移量拿0，20，20，20这样第二页的拿不到

**Comment by ShilongLee** [comment]
看看日志又没没有报错

**Comment by W-CLL** [comment]
我再看看

**Comment by W-CLL** [comment]
![image](https://github.com/user-attachments/assets/a52192f0-4975-4ac9-9a42-c8c43e99e461)
也看了一下官方接口，没什么区别，找不到原因，cookie能正常拿到其他接口数据，剩下是不是因为代理，我代理30秒一换

**Comment by yongplus** [comment]
抖音评论请求效率可以提升吗，目测每个请求耗时2s左右 官方ajax请求的200ms

**Comment by W-CLL** [comment]
> 抖音评论请求效率可以提升吗，目测每个请求耗时2s左右 官方ajax请求的200ms

兄弟，你有没有遇到我说的那个问题，拿不到第二页数据

**Comment by yongplus** [comment]
没有，但是数据不太对，偶尔有重复抓取的



Sent&nbsp;from&nbsp;my&nbsp;iPhone


------------------ 原始邮件 ------------------
From: CLL ***@***.***&gt;
发送时间: 11/06/2024, 15:01
To: ShilongLee/Crawler ***@***.***&gt;
抄送: Yong++ ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [ShilongLee/Crawler] 抖音评论 (Issue #74)





  
抖音评论请求效率可以提升吗，目测每个请求耗时2s左右 官方ajax请求的200ms
  
兄弟，你有没有遇到我说的那个问题，拿不到第二页数据

**Comment by W-CLL** [comment]
@yongplus 打扰一下，不好意思，可能问题有点多想问，1、你是登录账号了吗，还是直接从抖音网页上拿的cookie2、有使用代理吗 3、有没有改过请求参数（源代码的）

**Comment by yongplus** [comment]
> @yongplus 打扰一下，不好意思，可能问题有点多想问，1、你是登录账号了吗，还是直接从抖音网页上拿的cookie2、有使用代理吗 3、有没有改过请求参数（源代码的）

抖音网页版复制的cookie字段，没用代理（爬的量非常少） 没改过源码用的docker安装

**Comment by W-CLL** [comment]
> > @yongplus 打扰一下，不好意思，可能问题有点多想问，1、你是登录账号了吗，还是直接从抖音网页上拿的cookie2、有使用代理吗 3、有没有改过请求参数（源代码的）
> 
> 抖音网页版复制的cookie字段，没用代理（爬的量非常少） 没改过源码用的docker安装

好的，谢谢了，我找出问题了，我用无头拿的cookie,而且用了代理，估计ip不干净，就一直不行，又测了一遍，我直接从网页复制下来，也没用代理，的确是可以拿到很多页

**Comment by GreyJeremyji** [comment]
> 抖音评论请求效率可以提升吗，目测每个请求耗时2s左右 官方ajax请求的200ms

这么快不会被封啊

**Comment by yongplus** [comment]
看了下源码，是代码逻辑导致的，每次请求会先请求首页获取webid，这个首页响应就在2s左右，目前我改了本地的，没有出现被封



Sent&nbsp;from&nbsp;my&nbsp;iPhone


------------------ 原始邮件 ------------------
From: GreyJeremyji ***@***.***&gt;
发送时间: 11/27/2024, 14:07
To: ShilongLee/Crawler ***@***.***&gt;
抄送: Yong++ ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [ShilongLee/Crawler] 抖音评论 (Issue #74)





  
抖音评论请求效率可以提升吗，目测每个请求耗时2s左右 官方ajax请求的200ms
  
这么快不会被封啊
