### ISSUE TITLE
ReferenceError: performance is not defined

### ISSUE THREAD

**Issue by tangxinglong** [ShilongLee/Crawler#9]
爬虫小白一枚，最开始报GBK的错误，我把读js的地方改成了execjs.compile(open('lib/js/douyin.js','r', encoding='utf-8').read())，但是调用/douyin/comments就会报execjs._exceptions.ProgramError: ReferenceError: performance is not defined，调用/account_list和add_account都没问题。

py版本是3.12.4

**Comment by changcheng7932** [comment]
运行douyin.js，开始也提示ReferenceError: performance is not defined，补上performance = {}后，又提示TypeError: Cannot read property '_u' of undefined，头条也是这个问题，这个还能补环境吗？

**Comment by RealHousailei** [comment]
> 运行douyin.js，开始也提示ReferenceError: performance is not defined，补上performance = {}后，又提示TypeError: Cannot read property '_u' of undefined，头条也是这个问题，这个还能补环境吗？

试下加上这个

const {performance} = require('perf_hooks');

**Comment by ShilongLee** [comment]
已经更新为纯算，现可用
